config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'terms_and_conditions', to: 'welcome#terms_and_conditions', as: 'terms_and_conditions'
  post '/terms_and_conditions', to: 'welcome#accept_terms', as: 'accept_terms'

  # Rutas para Devise (autenticación de usuario)
  devise_for :users

  # Rutas estáticas
  root 'welcome#index'




  # Rutas para los modelos Motores y Mantenimientos
  resources :motors
  resources :mantenimientos

  # Otras rutas que puedas necesitar
end

app/models/mantenimiento.rb
class Mantenimiento < ApplicationRecord

end

app/controllers/mantenimientos_controller.rb
class MantenimientosController < ApplicationController
  load_and_authorize_resource

  before_action :set_mantenimiento, only: %i[ show edit update destroy ]

  # GET /mantenimientos or /mantenimientos.json
  def index
    @mantenimientos = Mantenimiento.all
  end

  # GET /mantenimientos/1 or /mantenimientos/1.json
  def show
  end

  # GET /mantenimientos/new
  def new
    @mantenimiento = Mantenimiento.new
  end

  # GET /mantenimientos/1/edit
  def edit
  end

  # POST /mantenimientos or /mantenimientos.json
  def create
    @mantenimiento = Mantenimiento.new(mantenimiento_params)

    respond_to do |format|
      if @mantenimiento.save
        format.html { redirect_to mantenimiento_url(@mantenimiento), notice: "Mantenimiento was successfully created." }
        format.json { render :show, status: :created, location: @mantenimiento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mantenimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mantenimientos/1 or /mantenimientos/1.json
  def update
    respond_to do |format|
      if @mantenimiento.update(mantenimiento_params)
        format.html { redirect_to mantenimiento_url(@mantenimiento), notice: "Mantenimiento was successfully updated." }
        format.json { render :show, status: :ok, location: @mantenimiento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mantenimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mantenimientos/1 or /mantenimientos/1.json
  def destroy
    @mantenimiento.destroy

    respond_to do |format|
      format.html { redirect_to mantenimientos_url, notice: "Mantenimiento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mantenimiento
      @mantenimiento = Mantenimiento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mantenimiento_params
      params.require(:mantenimiento).permit(:tipo_motor, :tipo_mantenimiento, :motor_id, :ciudad, :materiales, :fecha_mantenimiento, :tecnico_email)
    end
end

app/helpers/mantenimientos_helper.rb
module MantenimientosHelper
end

app/views/mantenimientos/_form.html.erb
<%= form_with(model: mantenimiento) do |form| %>
  <% if mantenimiento.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mantenimiento.errors.count, "error") %> prohibited this mantenimiento from being saved:</h2>

      <ul>
        <% mantenimiento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :motor_id, "Seleccionar Motor:", style: "display: block" %>
    <%= form.collection_select :motor_id, Motor.all, :id, :nombre, { prompt: "Seleccionar un motor" } %>
  </div>

  <div>
    <%= form.label :tipo_motor, style: "display: block" %>
    <%= form.select :tipo_motor, options_for_select(["REAC", "TURBO"], selected: mantenimiento.tipo_motor), {}, { class: "motor-type-select" } %>
  </div>

  <div>
    <%= form.label :tipo_mantenimiento, style: "display: block" %>
    <%= form.select :tipo_mantenimiento, options_for_select(["Preventivo", "Correctivo"], selected: mantenimiento.tipo_mantenimiento) %>
  </div>

  <div>
    <%= form.label :ciudad, style: "display: block" %>
    <%= form.select :ciudad, options_for_select(["Santiago", "Valparaíso", "Concepción", "Antofagasta", "Iquique", "Arica", "La Serena", "Punta Arenas", "Rancagua", "Temuco", "Chillán", "Curicó", "Osorno", "Copiapó", "Quillota", "Talca", "Calama", "Los Ángeles", "Puerto Montt"], selected: mantenimiento.ciudad) %>
  </div>

 <div>
  <%= form.label :materiales, style: "display: block" %>
  <%= form.select :materiales, options_for_select([
    "Aceite lubricante",
    "Filtro de aire",
    "Bujías de encendido",
    "Aceite hidráulico",
    "Aceite de turbina",
    "Aceite de motor",
    "Filtros de aceite",
    "Bujías de ignición",
    "Bujías de precalentamiento",
    "Filtros de combustible",
    "Bujes",
    "Cojinetes",
    "Válvulas",
    "Sellos",
    "Empaquetaduras",
    "Tornillos",
    "Arandelas",
    "Tuercas",
    "Juntas tóricas",
    "Correas de transmisión"
  ], selected: mantenimiento.materiales), { multiple: true, size: 3 } %>
</div>


  <div>
    <%= form.label :fecha_mantenimiento, style: "display: block" %>
    <%= form.date_field :fecha_mantenimiento %>
  </div>

  <div>
    <%= form.label :tecnico_email, style: "display: block" %>
    <%= form.text_field :tecnico_email, value: current_user.email, readonly: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mantenimientos/_mantenimiento.html.erb
<div id="<%= dom_id mantenimiento %>">
  <p>
    <strong>Tipo motor:</strong>
    <%= mantenimiento.tipo_motor %>
  </p>

  <p>
    <strong>Tipo mantenimiento:</strong>
    <%= mantenimiento.tipo_mantenimiento %>
  </p>

  <p>
    <strong>Motor:</strong>
    <%= mantenimiento.motor_id %>
  </p>

  <p>
    <strong>Ciudad:</strong>
    <%= mantenimiento.ciudad %>
  </p>

  <p>
    <strong>Materiales:</strong>
    <%= mantenimiento.materiales %>
  </p>

  <p>
    <strong>Fecha mantenimiento:</strong>
    <%= mantenimiento.fecha_mantenimiento %>
  </p>

  <p>
    <strong>Tecnico email:</strong>
    <%= mantenimiento.tecnico_email %>
  </p>

</div>

app/views/mantenimientos/edit.html.erb
<h1>Editing mantenimiento</h1>

<%= render "form", mantenimiento: @mantenimiento %>

<br>

<div>
  <%= link_to "Show this mantenimiento", @mantenimiento %> |
  <%= link_to "Back to mantenimientos", mantenimientos_path %>
</div>

app/views/mantenimientos/index.html.erb
<style>
  .thumbnail {
    width: 50px;
    height: 50px;
  }

  .table-container {
    max-height: 300px;
    overflow-y: auto;
  }

  /* Estilo dark para la tabla */
  .table-dark {
    background-color: #343a40; /* Cambia este color según tu preferencia */
    color: #fff; /* Color de texto en la tabla */
  }
</style>

<p style="color: green"><%= notice %></p>

<h1>Mantenimientos</h1>

<div class="card glass text-white">
  <div class="card-body">
    <div class="table-container scrollable-card">
      <table class="table table-bordered table-responsive table-dark">
        <thead>
          <tr>
            <th>Tipo de Motor</th>
            <th>Tipo de Mantenimiento</th>
            <th>Ciudad</th>
            <th>Materiales</th>
            <th>Fecha de Mantenimiento</th>
            <th>Técnico Email</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @mantenimientos.each do |mantenimiento| %>
            <tr>
              <td><%= mantenimiento.tipo_motor %></td>
              <td><%= mantenimiento.tipo_mantenimiento %></td>
              <td><%= mantenimiento.ciudad %></td>
              <td><%= mantenimiento.materiales %></td>
              <td><%= mantenimiento.fecha_mantenimiento.strftime("%Y-%m-%d") %></td>
              <td><%= mantenimiento.tecnico_email %></td>
              <td class="d-flex justify-content-center">
                <%= link_to "<i class='fas fa-eye'></i>".html_safe, mantenimiento, class: "btn btn-primary mx-1", title: "Ver" %>
                <%= link_to "<i class='fas fa-edit'></i>".html_safe, edit_mantenimiento_path(mantenimiento), class: "btn btn-secondary mx-1", title: "Editar" %>
                <%= link_to "<i class='fas fa-trash'></i>".html_safe, mantenimiento, method: :delete, data: { confirm: "¿Estás seguro?" }, class: "btn btn-danger mx-1", title: "Eliminar" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= link_to "Nuevo mantenimiento", new_mantenimiento_path, class: "btn btn-success" %>

app/views/mantenimientos/new.html.erb
<h1>New mantenimiento</h1>

<%= render "form", mantenimiento: @mantenimiento %>

<br>

<div>
  <%= link_to "Back to mantenimientos", mantenimientos_path %>
</div>

app/views/mantenimientos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mantenimiento %>

<div>
  <%= link_to "Edit this mantenimiento", edit_mantenimiento_path(@mantenimiento) %> |
  <%= link_to "Back to mantenimientos", mantenimientos_path %>

  <%= button_to "Destroy this mantenimiento", @mantenimiento, method: :delete %>
</div>