config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'terms_and_conditions', to: 'welcome#terms_and_conditions', as: 'terms_and_conditions'
  post '/terms_and_conditions', to: 'welcome#accept_terms', as: 'accept_terms'

  # Rutas para Devise (autenticación de usuario)
  devise_for :users

  # Rutas estáticas
  root 'welcome#index'




  # Rutas para los modelos Motores y Mantenimientos
  resources :motors
  resources :mantenimientos

  # Otras rutas que puedas necesitar
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">
      <i class="fas fa-shuttle-space"></i> JetMaintain
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-around" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Inicio', root_path, class: 'nav-link active', aria_current: 'page' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Motores', motors_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Mantenimientos', mantenimientos_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Términos y Condiciones', terms_and_conditions_path, class: 'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <span class="nav-link text-warning">Bienvenid@ <%= current_user.email %> (Rol: <%= current_user.role.titleize %>)</span>
          </li>
          <li class="nav-item">
            <%= link_to 'Cerrar sesión', destroy_user_session_path, class: 'nav-link', method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Iniciar sesión', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>