config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'terms_and_conditions', to: 'welcome#terms_and_conditions', as: 'terms_and_conditions'
  post '/terms_and_conditions', to: 'welcome#accept_terms', as: 'accept_terms'

  # Rutas para Devise (autenticación de usuario)
  devise_for :users

  # Rutas estáticas
  root 'welcome#index'




  # Rutas para los modelos Motores y Mantenimientos
  resources :motors
  resources :mantenimientos

  # Otras rutas que puedas necesitar
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @mantenimientos = Mantenimiento.all # Obtén todos los mantenimientos aquí
    @motors = Motor.all # Obtén todos los motores aquí
  end

  def terms_and_conditions

  end

  def accept_terms
    # Realiza aquí cualquier acción que necesites al aceptar los términos.
    # Puedes almacenar el estado de aceptación en la base de datos o
    # realizar otras operaciones necesarias.
    # Después de eso, puedes redirigir al usuario a la página principal u otra página.

    flash[:notice] = "Has aceptado los términos y condiciones."

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<style >
  .scrollable-card {
  max-height: 600px;
  overflow-y: auto;
}
</style>
<div class="container mt-5">
  <h1 class="display-4 text-center mb-4">¡Bienvenido a JetMaintain!</h1>
  <p class="lead text-center">Tu solución de mantenimiento para motores de avión</p>
</div>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 ">
      <div class="card glass text-white scrollable-card">
        <div class="card-header">
          Mantenimientos Recientes
        </div>
        <div class="card-body">
          <% @mantenimientos.each do |mantenimiento| %>
            <h5 class="card-title"><%= mantenimiento.tipo_motor %></h5>
            <p class="card-text">
              Tipo de Mantenimiento: <%= mantenimiento.tipo_mantenimiento %><br>
              Ciudad: <%= mantenimiento.ciudad %><br>
              Fecha de Mantenimiento: <%= mantenimiento.fecha_mantenimiento.strftime("%Y-%m-%d") %>
            </p>
          <% end %>
          <%= link_to "Ver todos los mantenimientos", mantenimientos_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card glass text-white scrollable-card">
        <div class="card-header">
          Motores Disponibles
        </div>
        <div class="card-body">
          <% @motors.each do |motor| %>
            <h5 class="card-title"><%= motor.nombre %></h5>
            <p class="card-text">
              Tipo de Equipo: <%= motor.tipo_equipo %><br>
              Descripción: <%= motor.description %><br>
              Usuario: <%= motor.user.email if motor.user %>
            </p>
          <% end %>
          <%= link_to "Ver todos los motores", motors_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/terms_and_conditions.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-8">
      <div class="glass card text-white">
        <div class="card-body text-center">
          <h2 class="card-title">Términos y Condiciones de Uso de JetMaintain</h2>
          <p class="card-text">Por favor, lea detenidamente estos Términos y Condiciones de Uso ("Términos") antes de utilizar la aplicación web JetMaintain (en adelante "nosotros" o "nuestra").</p>

          <h3>Aceptación de los Términos</h3>

          <p>Al acceder o utilizar JetMaintain, usted acepta estar sujeto a estos Términos. Si no está de acuerdo con alguno de estos Términos, no utilice nuestra aplicación.</p>

          <h3>Uso de la Aplicación</h3>

          <p>Usted acepta utilizar JetMaintain únicamente con fines legales y de acuerdo con estos Términos. No debe utilizar la aplicación de ninguna manera que pueda dañar, deshabilitar, sobrecargar o perjudicar la aplicación o interferir con el uso de la misma por parte de terceros.</p>

          <h3>Privacidad</h3>

          <p>Su uso de JetMaintain también está sujeto a nuestra Política de Privacidad, que puede encontrar en [enlace a la política de privacidad]. Al utilizar la aplicación, usted acepta nuestras prácticas de recopilación y uso de información como se describe en la Política de Privacidad.</p>

          <h3>Modificaciones</h3>

          <p>Nos reservamos el derecho de modificar o revisar estos Términos en cualquier momento. Cualquier cambio entrará en vigencia inmediatamente después de la publicación en esta página. Le recomendamos que revise periódicamente los Términos para estar al tanto de las actualizaciones.</p>

          <h3>Aceptación de los Términos</h3>

          <p>Al hacer clic en el botón "Acepto" a continuación, usted confirma que ha leído, entendido y aceptado estos Términos y Condiciones de Uso.</p>

          <!-- Formulario para aceptar los términos -->
         <%= form_tag accept_terms_path, id: 'accept-terms-form' do %>
  <%= hidden_field_tag :accepted, true %>
  <%= submit_tag "He leído y acepto los términos", class: "btn btn-primary", id: "accept-button" %>
<% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const acceptButton = document.querySelector('#accept-button');

    acceptButton.addEventListener('click', function(event) {
      event.preventDefault();

      Swal.fire({
        title: '¿Estás seguro?',
        text: '¿Quieres aceptar los términos y condiciones?',
        icon: 'question',
        showCancelButton: true,
        confirmButtonText: 'Sí, aceptar',
        cancelButtonText: 'Cancelar'
      }).then((result) => {
        if (result.isConfirmed) {
          // Si el usuario confirma, envía el formulario
          document.querySelector('#accept-terms-form').submit();
        } else {
          Swal.fire('Términos no aceptados', 'Debes aceptar los términos y condiciones para continuar.', 'error');
        }
      });
    });
  });
</script>