config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'terms_and_conditions', to: 'welcome#terms_and_conditions', as: 'terms_and_conditions'
  post '/terms_and_conditions', to: 'welcome#accept_terms', as: 'accept_terms'

  # Rutas para Devise (autenticación de usuario)
  devise_for :users

  # Rutas estáticas
  root 'welcome#index'




  # Rutas para los modelos Motores y Mantenimientos
  resources :motors
  resources :mantenimientos

  # Otras rutas que puedas necesitar
end

app/models/motor.rb
class Motor < ApplicationRecord
  enum tipo_equipo: {
    'Motor a reacción' => 'REAC',
    'Motor turbohélice' => 'TURBO'
  }
  has_many :mantenimientos, dependent: :destroy  # Esto asume que tienes una relación con el modelo Mantenimiento
  validates :nombre, format: { with: /\A(REAC|TURBO)-\d+\z/, message: "debe seguir el formato REAC-numero o TURBO-numero" }
  belongs_to :user
  has_one_attached :image
end

app/controllers/motors_controller.rb
class MotorsController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to motors_path, alert: exception.message
  end
  before_action :set_motor, only: %i[ show edit update destroy ]

  # GET /motors or /motors.json
  def index
    @motors = Motor.all
  end

  # GET /motors/1 or /motors/1.json
  def show
  end

  # GET /motors/new
  def new
    @motor = Motor.new
  end

  # GET /motors/1/edit
  def edit
  end

  # POST /motors or /motors.json
  def create
    @motor = Motor.new(motor_params)

    respond_to do |format|
      if @motor.save
        format.html { redirect_to motor_url(@motor), notice: "Motor was successfully created." }
        format.json { render :show, status: :created, location: @motor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motors/1 or /motors/1.json
  def update
    respond_to do |format|
      if @motor.update(motor_params)
        format.html { redirect_to motor_url(@motor), notice: "Motor was successfully updated." }
        format.json { render :show, status: :ok, location: @motor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motors/1 or /motors/1.json
  def destroy
    @motor.destroy

    respond_to do |format|
      format.html { redirect_to motors_url, notice: "Motor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motor
      @motor = Motor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def motor_params
      params.require(:motor).permit(:tipo_equipo, :nombre, :description, :image, :user_id)
    end
end

app/helpers/motors_helper.rb
module MotorsHelper
end

app/views/motors/_form.html.erb
<%= form_with(model: motor) do |form| %>
  <% if motor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(motor.errors.count, "error") %> prohibited this motor from being saved:</h2>

      <ul>
        <% motor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tipo_equipo, style: "display: block" %>
    <%= form.select :tipo_equipo, Motor.tipo_equipos.keys %>
  </div>

  <div>
  <%= form.label :nombre, style: "display: block" %>
  <%= form.text_field :nombre, value: 'REAC', placeholder: 'Ingrese el número' %>
</div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
  <%= form.label :user_id, style: "display: block" %>
  <%= form.collection_select :user_id, User.all, :id, :email %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/motors/_motor.html.erb
<style>
  .thumbnail {
    width: 50px;
    height: 50px;
  }

  .table-container {
    max-height: 300px;
    overflow-y: auto;
  }
</style>

<div class="table-container">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Tipo equipo</th>
        <th>Nombre</th>
        <th>Description</th>
        <th>Image</th>
        <th>User</th>
        <th>Rol</th>
        <th>Detalles</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= motor.tipo_equipo %></td>
        <td><%= motor.nombre %></td>
        <td><%= motor.description %></td>
        <td>
          <% if motor.image.attached? %>
            <%= image_tag motor.image, class: "thumbnail" %>
          <% else %>
            <i class="fas fa-fax fa-2x"></i> <!-- Ícono de motor de Font Awesome -->
          <% end %>
        </td>
        <td><%= motor.user.email if motor.user %></td>
        <td><%= motor.user.role.titleize if motor.user %></td>
        <td>
          <%= link_to motor_path(motor) do %>
            <i class="fas fa-info-circle fa-2x"></i>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/motors/edit.html.erb
<h1>Editing motor</h1>

<%= render "form", motor: @motor %>

<br>

<div>
  <%= link_to "Show this motor", @motor %> |
  <%= link_to "Back to motors", motors_path %>
</div>

app/views/motors/index.html.erb
<style>
  .thumbnail {
    width: 50px;
    height: 50px;
  }

  .table-container {
    max-height: 300px;
    overflow-y: auto;
  }

  /* Estilo dark para la tabla */
  .table-dark {
    background-color: #343a40; /* Cambia este color según tu preferencia */
    color: #fff; /* Color de texto en la tabla */
  }

  /* Estilo para los íconos */
  .btn-icon {
    font-size: 20px;
    margin-right: 5px; /* Espacio entre ícono y texto */
  }
  .scrollable-card::-webkit-scrollbar {
  width: 12px;
  background-color: #F5F5F5;
}

.scrollable-card::-webkit-scrollbar-thumb {
  border-radius: 10px;
  -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.1);
  background-color: #4285F4;
}

.scrollable-card {
  scrollbar-color: #4285F4 #F5F5F5;
}
</style>

<p style="color: green"><%= notice %></p>
<h1>Motores</h1>

<div class="glass card  text-white">
  <div class="card-body">
    <div class="table-container scrollable-card">
      <table class="table table-bordered table-responsive table-dark ">
        <thead>
          <tr>
            <th>Tipo Equipo</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Image</th>
            <th>User</th>
            <th>Rol</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @motors.each do |motor| %>
            <tr>
              <td><%= motor.tipo_equipo %></td>
              <td><%= motor.nombre %></td>
              <td><%= motor.description %></td>
              <td>
                <% if motor.image.attached? %>
                  <%= image_tag motor.image, class: "thumbnail" %>
                <% else %>
                  <i class='fas fa-fax fa-2x'></i>
                <% end %>
              </td>
              <td><%= motor.user.email if motor.user %></td>
              <td><%= motor.user.role.titleize if motor.user %></td>
              <td>
                <%= link_to "<i class='fas fa-eye btn-icon'></i>".html_safe, motor, class: "btn btn-primary", title: "Ver" %>
                <%= link_to "<i class='fas fa-edit btn-icon'></i>".html_safe, edit_motor_path(motor), class: "btn btn-secondary", title: "Editar" %>
                <%= link_to "<i class='fas fa-trash btn-icon'></i>".html_safe, motor, method: :delete, data: { confirm: "¿Estás seguro?" }, class: "btn btn-danger", title: "Eliminar" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= link_to "Nuevo motor", new_motor_path, class: "btn btn-success" %>

app/views/motors/new.html.erb
<h1>New motor</h1>

<%= render "form", motor: @motor %>

<br>

<div>
  <%= link_to "Back to motors", motors_path %>
</div>

app/views/motors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @motor %>

<div>
  <%= link_to "Edit this motor", edit_motor_path(@motor) %> |
  <%= link_to "Back to motors", motors_path %>

  <%= button_to "Destroy this motor", @motor, method: :delete %>
</div>